### ISSUE TITLE
getCurrentUser's getGooogleApiClient dealing with null

### ISSUE THREAD

**Issue by ersin-ertan** [googlesamples/easygoogle#26]
With the calling code of:

``` java
        if (google != null) {
            SignIn signIn = google.getSignIn();
            if (signIn != null) {
                boolean isS = signIn.isSignedIn();
                if (isS) { ...
```

And SignIn.class code of:

``` java
   public GoogleSignInAccount getCurrentUser() {
        OptionalPendingResult opr = Auth.GoogleSignInApi.silentSignIn(this.getFragment().getGoogleApiClient());
        return opr.isDone()?((GoogleSignInResult)opr.get()).getSignInAccount():null;
    }

    public boolean isSignedIn() {
        return this.getCurrentUser() != null;
    }
```

The GacFragment.class 

``` java
    public GoogleApiClient getGoogleApiClient() {
        return this.mGoogleApiClient;
    }
```

is returning null and crashing.

```
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.gms.common.api.Api$zzb com.google.android.gms.common.api.GoogleApiClient.zza(com.google.android.gms.common.api.Api$zzc)' on a null object reference
                      at com.google.android.gms.auth.api.signin.internal.zzc.zza(Unknown Source)
                      at com.google.android.gms.auth.api.signin.internal.zzc.silentSignIn(Unknown Source)
                      at pub.devrel.easygoogle.gac.SignIn.getCurrentUser(SignIn.java:181)
                      at pub.devrel.easygoogle.gac.SignIn.isSignedIn(SignIn.java:195)
```

Shouldn't it return false?

**Comment by samtstern** [comment]
@ersin-ertan where are you calling `isSignedIn` in your code?

**Comment by ersin-ertan** [comment]
Google is injected into then called from the onCreate within a different activity of its initial creation/init. The user could have signed out and still be viewing the contents of the current activity.

**Comment by samtstern** [comment]
@ersin-ertan I think you will have better results checking in `onStart` when everything has been fully initialized.

**Comment by ersin-ertan** [comment]
Thank you, untested(due to change of implementation) but noted.
